management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
server:
  port: ${PORT:0}       
spring:
  application:
    name: devglan-gateway 
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id}:${random.value}
    
