server:
  port: 8761
spring:
  application:
    name: service-discovery
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    enabled: true
    eureka-server-connect-timeout-seconds: 60