
test:
    greeting: ${test.description}
    name: Configuration 
    description: Welcome to Spring Boot ${test.name}
    names: Srinivas,Nandini,Bhaumik
    dbdetails: {
                  driver: 'OracleDriver',
                  username : 'system',
                  password : 'bhaumik23'
               }

db:
  driver : OracleDriver
  username : system1
  password : bhaumik23

management:
  endpoints:
    web:
      exposure:
        include:

server:
  port: 3001
  
spring:
  profiles:
    active:
    - test