#server:
  #port: ${PORT:0}
  
server:
  port: 3006
  
#spring:
  #application:
    #name: logicbig-spring-cloud-config-client
    
#eureka:
  #instance:
    #instance-id: ${spring.application.name}:${spring.application.instance_id}:${random.value}
