server:
  port: ${PORT:0}
  
spring:
  application:
    name: logicbig-spring-cloud-config-client
    
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id}:${random.value}
