spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/only2dhir/config-repo.git
    
server:
  port: 3008
  
#eureka:
  #instance:
    #instance-id: ${spring.application.name}:${spring.application.instance_id}:${random.value}
    

    
    
