server:
  port: ${PORT:0}
  
spring:
  application:
    name: logicbig-spring-cloud-config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/MicroService_Workspace/Configuration
  profiles:
    active: native
    
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id}:${random.value}


